services:
  - type: web
    name: openhands
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    environmentVariables:
      - key: LLM_MODEL
        value: "anthropic/claude-3-5-sonnet-20241022"
      - key: LLM_API_KEY
        fromSecret: LLM_API_KEY
      - key: WORKSPACE_BASE
        value: "/tmp/workspace"
      - key: SANDBOX_RUNTIME_CONTAINER_IMAGE
        value: "openhands/sandbox:v0.8.3"
