services:
  - type: web
    name: openhands
    runtime: python3  # ← No Docker = No Docker errors
    pythonVersion: "3.12"
    plan: free
    
    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-dev
      cd frontend && npm ci && npm run build
    
    startCommand: "poetry run uvicorn openhands.server.listen:app --host 0.0.0.0 --port $PORT"
    
    envVars:
      # LLM Configuration  
      - key: ANTHROPIC_API_KEY
        sync: false
      
      # Local runtime (no Docker)
      - key: SANDBOX_TYPE
        value: local
      - key: RUNTIME
        value: local
      - key: WORKSPACE_BASE
        value: /tmp/workspace
      - key: FILE_STORE_PATH
        value: /tmp/openhands
      
      # Performance optimizations
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "1"
