services:
  - type: web
    name: openhands
    runtime: python3
    pythonVersion: "3.12"
    plan: free
    buildCommand: pip install poetry gunicorn && poetry config virtualenvs.create false && poetry install --no-dev && cd frontend && npm ci && npm run build
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SANDBOX_TYPE
        value: local
      - key: RUNTIME
        value: local
      - key: DISABLE_DOCKER
        value: "true"
